name: deploy-docker

on: [workflow_dispatch]

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'

  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get tag
        run: |
          git fetch
          git describe --tags --abbrev=0 --always
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push full
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: fastsurfer:latest, fastsurfer:${{ steps.get_version.outputs.VERSION }}
          file: Docker/Dockerfile
      - name: Build and push segonly
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: fastsurfer:segonly_${{ steps.get_version.outputs.VERSION }}
          file: Docker/Dockerfile_FastSurferCNN
      - name: Build and push surfonly
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: fastsurfer:surfonly_${{ steps.get_version.outputs.VERSION }}
          file: Docker/Dockerfile_reconsurf